services:
  - type: web
    name: nex-music-website
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --threads 4 --timeout 60
    healthCheckPath: /health
